version: "3.3"
services:
  web:
    image: php:7.3-apache
    container_name: st_tracker
    ports:
      - '10000:80'
    volumes:
      - ./app:/var/www/html/
      - ./data_sat:/home/tracker/data_sat
